print("I have a class of 33 students.")
print("There are 11 girls, so that means...")
# subtraction (33 - 11 = 22)
print(f"there are {33 - 11} boys.")
# division (11 / 33 = 0.333...)
print(f"That means {round(11 / 33, 2)} % are girls...")
# subtraction and division (33 - 11 = 22, 22 / 33)
print("and {} % are boys.".format(round((33 - 11) / 33, 2)))
print()

print("If we made groups of six...")
# floor (round down) division (33 // 6 = 5)
print(f"There would be {33 // 6} groups of six.")
# modulus (remainder) (33 % 6 = 3)
print(f"And then a smaller group of {33 % 6} people.")
# prints '-' 30 times
print("-" * 30)
print("If we had 17 apples and 3 people...")
# floor (round down) division (17 // 3 = 5)
print(f"Each person would get {17 // 3} whole apples.")
# modulus (remainder) (17 % 3 = 2)
print("There would be " + str(17 % 3) + " apples remaining.")
print()

print("If we charged each person $2 each for their 5 apples..")
# multiplication (2 * 5 = 10)
print("they would each pay ${}.".format(2 * 5))